### ISSUE TITLE
PLUGIN Tidak Bisa Diaktifkan

### ISSUE THREAD

**Issue by irham9494h** [agusnurwanto/wp-sipd#3]
terjadi error pada saat akan mengaktifkan plugin, akan tetapi pada saat menginstall plugin berhasil.

PHP versi 7.2.x
MySQL  versi 5.7.x
Wordpress versi 5.6.x

![image](https://user-images.githubusercontent.com/14119912/107616078-4b52c600-6c88-11eb-95c0-fde1bc8ca0c8.png)

![image](https://user-images.githubusercontent.com/14119912/107616311-c4521d80-6c88-11eb-9b24-de3801042bce.png)

Mohon bantuannya @agusnurwanto

**Comment by agusnurwanto** [comment]
download pluginnya dari master zip mas. jangan dari release. saya lupa belum release yg terbaru soalnya. https://github.com/agusnurwanto/wp-sipd/releases/tag/v1.5 barusan saya relase yg terbaru. atau langsung dari link master zip ini https://github.com/agusnurwanto/wp-sipd/archive/master.zip
